; Combined NMEA 2000 + BLE gateway on Waveshare ESP32-P4-WIFI6-POE-ETH.

[platformio]
default_envs = dual_gateway

[env:dual_gateway]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = espidf, arduino

board = esp32-p4
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = ../../examples/basic_gateway/p4_16mb.csv

upload_speed = 2000000
monitor_speed = 115200
build_unflags = -Werror=reorder

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D USE_ESP_IDF_LOG
    -D SENSESP_SSL_SUPPORT=1
    -DBOARD_HAS_PSRAM

lib_ldf_mode = deep

lib_deps =
    https://github.com/SignalK/SensESP.git#main
    symlink://../../
    https://github.com/dirkwa/sensesp-ble-gateway.git
    esp_websocket_client=https://components.espressif.com/api/downloads/?object_type=component&object_id=dbc87006-9a4b-45e6-a6ab-b286174cb413
